name: BETA Build site

on:
  pull_request:
    branches: [ "main" ] # Изменено на "main"
    types: [closed] # Добавлено условие "closed"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Проверяем, что PR был смержен
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # IP или домен вашего сервера
          username: ${{ secrets.USERNAME }} # Имя пользователя на сервере
          key: ${{ secrets.PRIVATE_KEY }} # Приватный SSH ключ для доступа к серверу
          script: |
            cd ~/domains/beta.foxworld.ru # Путь к папке проекта на сервере
            git pull origin main # Обновляем код из GitHub
            npm install # Устанавливаем зависимости
            npm run build # Собираем проект
            mkdir -p ~/domains/beta.foxworld.ru/tmp && touch ~/domains/beta.foxworld.ru/tmp/restart.txt
