name: Release note (Discord)
on:
  release:
    types: [published]
jobs:
  build:
    name: Send note
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
          DISCORD_USERNAME: "FoxWorld"
          DISCORD_AVATAR: "https://cdn.discordapp.com/avatars/1300520523725410425/e8b382f3c4cbecc0da5632e31ebf501a.png"
          DISCORD_EMBEDS: |
            [
              {
                "description": "## ```${{ github.event.release.name }}```\n${{ github.event.release.body}}",
                "color": 16756866,
                "footer": {
                    "text": "— С любовью к своему делу, команда разработки FoxWorld.",
                    "icon_url": "https://cdn.discordapp.com/avatars/1300520523725410425/e8b382f3c4cbecc0da5632e31ebf501a.png"
                },
                "thumbnail": {
                    "url": "https://refugiacraft.de/chibi.php?image=PWNight"
                },
                "fields": []
              }
            ]
        uses: Ilshidur/action-discord@master
