name: Release note (Discord)

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: EhsanFox/djs-actions@0.1.0
        with:
          id: ${{ secrets.webhook_id }}
          token: ${{ secrets.webhook_token }}
          title: ${{ github.event.release.name }}
          description: ${{ github.event.release.body }}
          color: "ffb082"
          footer: "— С любовью к своему делу, команда разработки FoxWorld."
          footer_icon: "https://media.discordapp.net/attachments/1053188398573166652/1279677459541000202/852d96957e5a13fa.jpg?ex=6767a681&is=67665501&hm=f82d4d87456433c2016&"
