name: Release note (Discord)
on:
  release:
    types: [published]
jobs:
  build:
    name: Send note
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: Zmicier14/discord-webhook@v1.0.6
        with:
            severity: info
            color: '#ff00aa'
            description: "## ${{ github.event.release.name }}"
            details: "{{ github.event.release.body}}"
            webhookUrl: ${{ secrets.WEBHOOK }}
