name: Release note (Discord)
on:
  release:
    types: [published]
jobs:
  build:
    name: Send note
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        id: discordAction
        uses: Poss111/discord-hook-action@v1.6.12
        with:
          discord-hook-url: ${{ secrets.WEBHOOK }}
          title: ${{ github.event.release.name }}
          message: ${{ github.event.release.body }}
