name: Notify about new release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: actions-ecosystem/discord@v2  # Assuming the new repository is actions-ecosystem/discord
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **${{ github.event.release.name }}**
            ${{ github.event.release.body }}
